config/routes.rb
Rails.application.routes.draw do

  match '/home', to: 'ski#home',via:'get'
  match '/about', to: 'ski#about',via:'get'
  match '/help', to: 'ski#help',via:'get'
  match '/contact', to: 'ski#contact',via:'get'
  match '/boards/list', to: 'boards#list',via:'get'
  resources :boards

end

app/models/board.rb
class Board < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    #puts t Board.human_attribute_name(:gender)
    @boards = Board.all
  end

  def list
    @boards = Board.all
  end
  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:gender, :name, :price, :img_url, :favorite, :ApproxWeight, :RidingStyle, :RidingLevel, :AvailableWidths, :Manufacturedin, :Shape, :CamberProfile, :Stance, :OnSnowFeel, :Powder, :TurnInitiation, :Speed, :UnevenTerrain, :EdgeHold, :Flex, :Carving, :Switch, :Jibbing, :Pipe, :Jumps)
    end
end

app/controllers/ski_controller.rb
class SkiController < ApplicationController
  def home
  end
  def help

  end
  def about
  end
  def concate

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
  $global_variable  = {"Locked In"=>"5","Semi-Catchy"=>"4","Stable"=>"3","Semi-Stable"=>"2","Loose"=>"1","Excellent"=>"5","Great"=>"4","Good"=>"3","Average"=>"2","Poor"=>"1","Very Easy"=>"5","Easy"=>"4","Moderate"=>"3","Semi-Challenging"=>"2","Challenging"=>"1","Excellent"=>"5","Great"=>"4","Good"=>"3","Average"=>"2","Poor"=>"1","Icy to Med"=>"5","Hard to Soft"=>"4","Med to Soft"=>"3","Mostly Soft"=>"2","Soft Only"=>"1","Stiff"=>"5","Medium/Stiff"=>"4","Medium"=>"3","Soft"=>"2","Noodle"=>"1"}
  @img= "<img src=\"/img/snowflake.png\">"
  def self.getReviewsValues(key)
    #puts key
    return @img * $global_variable[key].to_i
 end
end

app/helpers/ski_helper.rb
module SkiHelper
  @imgfavorite = "<img class=\"favorite\" src=\"/img/favorite.png\">"
  def self.isfavorite(isf)
    puts isf
    if(isf.to_s =="1")
      puts @imgfavorite
      return @imgfavorite*1
    end
  end
end

app/views/boards/_form.html.erb
<style>
    label       { display:initial;cursor: pointer; color:#333; }
    .input-group-addon{ width:90px; text-align: left}
    .input-group
    {
        width:100%;
        margin-bottom: 5px;
    }
    .edit-item
    {
        padding-top: 5px;
        border-top: 1px solid #ddd;
        border-radius: 3px 3px 0 0;
        padding: 4px 12px 4px 12px;
        border: 1px solid #ddd;
    }

</style>


  <% if @board.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

        <ul>
          <% @board.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
<%= form_for(@board) do |f| %>
<div class="row">
    <div class="col-md-12">
      <div class="edit-item">
          <div class="input-group">
            <span class="input-group-addon"><%= f.label :name %> </span>
            <%= f.text_field :name,class:"form-control" %>
          </div>

          <div class="input-group">
            <span class="input-group-addon"><%= f.label :gender %></span>
            <%= f.text_field :gender,class:"form-control" %>
          </div>
        <div class="input-group">
          <span class="input-group-addon"><%= f.label :favorite %></span>
          <%= f.text_field :favorite,class:"form-control" %>
        </div>
          <div class="input-group">
            <span class="input-group-addon"><%= f.label :price %> $</span>
            <%= f.text_field :price,class:"form-control" %>
          </div>
          <div class="input-group">
            <span class="input-group-addon"><%= f.label :img_url %></span>
            <%= f.text_field :img_url,class:"form-control" %>
          </div>
       </div>
    </div>
  </div>
      <div class="row">
    <div class="col-md-6">
      <div class="edit-item">

        <div class="input-group">
          <span class="input-group-addon"><%= f.label :ApproxWeight %></span>
          <%= f.text_field :ApproxWeight,class:"form-control" %>
        </div>

        <div class="input-group">
          <span class="input-group-addon"><%= f.label :RidingStyle %></span>
          <%= f.text_field :RidingStyle,class:"form-control" %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><%= f.label :RidingLevel %></span>
          <%= f.text_field :RidingLevel,class:"form-control" %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><%= f.label :AvailableWidths %></span>
          <%= f.text_field :AvailableWidths,class:"form-control" %>
        </div>
      </div>
  </div>
  <div class="col-md-6">
    <div class="edit-item">

      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Manufacturedin %></span>
        <%= f.text_field :Manufacturedin,class:"form-control" %>
      </div>

      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Shape %></span>
        <%= f.text_field :Shape,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :CamberProfile %></span>
        <%= f.text_field :CamberProfile,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Stance %></span>
        <%= f.text_field :Stance,class:"form-control" %>
      </div>
    </div>
  </div>
</div>
<div class="row" style="margin-bottom: 2px;">
  <div class="col-md-6">
    <div class="edit-item">
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :OnSnowFeel %></span>
        <%= f.text_field :OnSnowFeel,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Powder %></span>
        <%= f.text_field :Powder,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :TurnInitiation %></span>
        <%= f.text_field :TurnInitiation,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Speed %></span>
        <%= f.text_field :Speed,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :UnevenTerrain %></span>
        <%= f.text_field :UnevenTerrain,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :EdgeHold %></span>
        <%= f.text_field :EdgeHold,class:"form-control" %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="edit-item">
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Flex %></span>
        <%= f.text_field :Flex,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Carving %></span>
        <%= f.text_field :Carving,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Switch %></span>
        <%= f.text_field :Switch,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Jibbing %></span>
        <%= f.text_field :Carving,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Pipe %></span>
        <%= f.text_field :Switch,class:"form-control" %>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><%= f.label :Jumps %></span>
        <%= f.text_field :Speed,class:"form-control" %>
      </div>
    </div>
  </div>
  </div>
<div class="actions row">
  <div class="col-md-12" style="text-align: right">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
  </div>
<% end %>

app/views/boards/_top.html.erb
<header class="navbar navbar-default" role="navigation" style="margin-bottom: 0px;">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#"><img src="http://thegoodride.com/assets/lg-gallery//logo-final.png" style="max-height:41px;"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">单板<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">男式</a></li>
            <li><a href="#">女式</a></li>
            <li class="divider"></li>
            <li><a href="#">关于单板的相关说明</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">固定器<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">男式</a></li>
            <li><a href="#">女式</a></li>
            <li class="divider"></li>
            <li><a href="#">关于固定器的相关说明</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">雪鞋<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">男式</a></li>
            <li><a href="#">女式</a></li>
            <li class="divider"></li>
            <li><a href="#">关于雪鞋的相关说明</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">配件<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">头盔</a></li>
            <li><a href="#">雪镜</a></li>
            <li><a href="#">摄像机</a></li>
            <li><a href="#">护具</a></li>
            <li><a href="#">手套</a></li>
            <li><a href="#">袜子</a></li>
            <li><a href="#">鞋垫</a></li>
            <li><a href="#">板架</a></li>
            <li><a href="#">教学</a></li>
            <li class="divider"></li>
            <li><a href="#">雪板专用工具箱</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">雪服<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">男式上衣</a></li>
            <li><a href="#">女式上衣</a></li>
            <li><a href="#">男式雪裤</a></li>
            <li><a href="#">女式雪裤</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">关于我们<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">关于网站</a></li>
            <li><a href="#">关于开发者</a></li>
            <li><a href="#">关于翻译</a></li>
            <li class="divider"></li>
            <li><a href="#">我们的朋友</a></li>
          </ul>
        </li>
        <li><a href="#">联系我们</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div>
</header>

app/views/boards/edit.html.erb
<%= render "top" %>
<div class="container" style="padding-top:10px;">
<%= render 'form' %>
<%= link_to '查看', @board %> |
<%= link_to '返回', boards_path %>
</div>

app/views/boards/index.html.erb
<%= render "top" %>
<div class="container" style="padding-top: 10px">
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th class="col-sm-9" >名称</th>
      <th  class="col-sm-1 text-center" >单价</th>
      <th  class="col-sm-2 text-center">编辑</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td class="col-sm-9"><%= board.name %></td>
        <td class="col-sm-1 text-center">$<%= board.price %></td>
        <td class="col-sm-2 text-center"><%= link_to '查看', board %>&nbsp;<%= link_to '编辑', edit_board_path(board) %>&nbsp;<%= link_to '删除', board, method: :delete, data: { confirm: '你确定删除吗？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '新建', new_board_path %>
</div>

app/views/boards/list.html.erb
<link rel="stylesheet" href="/css/jquery.coolfieldset.css">
<%= render "top" %>
<div id="wrap" class="container" role="document" style="width: 100% !important">
<div id="content" class="row">
<div id="main" class="" role="main">
<br>
<h1 id="title" style="margin-top: 0px; margin-bottom: 0px; font-size: 24px; line-height: 36px;
        font-weight: bold;"> Men's Snowboards</h1>
<%= render "left"%>
<div id="colright" style="margin: 0px 0px 0px 235px;">
  <div id="applications" class="image-grid" style="display: block;">
    <div class="board-reviews animate" data-id="3084">
      <a href="http://thegoodride.com/snowboard-reviews/apo-supreme-review-and-buying-advice">
        <div style="position: relative; width:160px;">
          <div class="price">
            <h5>
              $499</h5>
          </div>
          <img class="productthumb" src="http://thegoodride.com/assets/lg-gallery/apo/snowboards/supreme/slides/apo-supreme.jpg"
               alt="APO Supreme"></div>
        <h4 style="text-align: center;">
          APO Supreme</h4>
      </a>
    </div>

    <% @boards.each do |board| %>
        <div class="board-reviews animate" data-id="<%=board.id %>">
          <a href="http://thegoodride.com/snowboard-reviews/apo-supreme-review-and-buying-advice">
            <div style="position: relative; ">
              <%=raw SkiHelper.isfavorite(board.favorite) %>
              <div class="price">
                <h5>$<%= board.price %></h5>
              </div>
              <img class="productthumb" src="<%= board.img_url %>" alt="<%= board.name %>"></div>
            <h4 style="text-align:center;"><%= board.name %></h4>
          </a>
        </div>
    <% end %>
<script>
  $(document).ready(function(){
      regeditcheck();
  });
</script>
  </div>
</div>
</div>
</div>

</div>


app/views/boards/new.html.erb
<%= render "top" %>
<div class="container" style="padding-top:10px;">
<%= render 'form' %>
<%= link_to '返回', boards_path %>
</div>

app/views/boards/show.html.erb
<%= render "top" %>
<div id="wrap" class="container" role="document" >
  <div id="content" class="row">
     <div id="main" class="span24" role="main">
       <article class="post-3084 snowboardreviews type-snowboardreviews status-publish hentry" id="post-3084">
          <header>
            <div class="page-header">
             <h1 class="entry-title"><%= @board.name %> Review And Buying Advice</h1>
            </div>
          </header>
          <div class="row">
  <div class="span20">
  <div class="row" style="margin-bottom: 5px;">
    <div class="span6">
      <div class="module" style="text-align:center;">
        <div id="tweets" style="border-radius:3px 3px 0 0; border: 1px solid #ddd;">
          <div class="tweet" style="clear:both;">
            <p style="font-size: 16px;"><strong>Price US $<%= @board.price %></strong></p>
          </div>
          <div style="clear:both;"></div>
        </div>
        <div class="inner" style="position: relative;line-height: 0;  border-radius: 0 0 3px 3px; border-top: none;">
          <%=raw SkiHelper.isfavorite(@board.favorite) %>
          <a href="<%= @board.img_url %>" rel="lightbox"><img src="<%= @board.img_url %>" alt="<%= @board.name %>Review And Buying Advice" style="max-height:350px;"/></a>						</div>
        <script type='text/javascript'>
            /* <![CDATA[ */
            var JQLBSettings = {"showInfo":"1","fitToScreen":"0","resizeSpeed":"400","displayDownloadLink":"0","navbarOnTop":"0","resizeCenter":"","marginSize":"0","linkTarget":"_self","slideshowSpeed":"4000","help":"","prevLinkTitle":"previous image","nextLinkTitle":"next image","closeTitle":"close image gallery","image":"Image ","of":" of ","download":"Download","pause":"(pause slideshow)","play":"(play slideshow)"};
            /* ]]> */
        </script>
      </div>
    </div>
    <div class="span14">
<div class="row">
  <div class="span7">
    <!--<h2>Specs</h2>-->

    <div class="module">
      <div class="inner">
        <!--<h2 class="twitter">Specs</h2>-->
        <div id="tweets">
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Approx. Weight</strong></p>
            <p style="float:right"><%= @board.ApproxWeight %></p>
          </div>
          <div style="clear:both;"></div>
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Riding Style</strong></p>
            <p style="float:right"><%= @board.RidingStyle %></p>
          </div>
          <div style="clear:both;"></div>
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Riding Level</strong></p>
            <p style="float:right"><%= @board.RidingLevel %></p>
          </div>
          <div style="clear:both;"></div>
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Available Widths</strong></p>
            <p style="float:right"><%= @board.AvailableWidths %></p>
          </div>
          <div style="clear:both;"></div>
        </div>
      </div>
    </div><!-- /.module -->
  </div>
  <div class="span7">
    <!--<h2>Specs</h2>-->
    <div class="module">
      <div class="inner">
        <!--<h2 class="twitter">Specs</h2>-->
        <div id="tweets">
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Manufactured in</strong></p>
            <p style="float:right"><%= @board.Manufacturedin %></p>
          </div>
          <div style="clear:both;"></div>
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Shape</strong></p>
            <p style="float:right"><%= @board.Shape %></p>
          </div>
          <div style="clear:both;"></div>
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Camber Profile</strong></p>
            <p style="float:right"><%= @board.CamberProfile %></p>
          </div>
          <div style="clear:both;"></div>
          <div class="tweet" style="clear:both;">
            <p style="float:left"><strong>Stance</strong></p>
            <p style="float:right"><%= @board.Stance %></p>
          </div>
          <div style="clear:both;"></div>
        </div>
      </div>
    </div><!-- /.module -->
  </div>
</div>
<div class="row" style="margin-bottom: 2px;">
  <div class="span14">
    <!--<h2>How It Rides</h2>-->

    <div class="row">
      <div class="span7">
        <div class="module">
          <div class="inner">
            <div id="tweets">
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>On Snow Feel</strong></p>
                  <p><%= @board.OnSnowFeel %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.OnSnowFeel %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Powder</strong></p>
                  <p><%= @board.Powder %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Powder %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Turn Initiation</strong></p>
                  <p><%= @board.TurnInitiation %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.TurnInitiation %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Speed</strong></p>
                  <p><%= @board.Speed %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Speed %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Uneven Terrain</strong></p>
                  <p><%= @board.UnevenTerrain %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.UnevenTerrain %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Edge Hold</strong></p>
                  <p><%= @board.EdgeHold %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.EdgeHold %>
                </div>
              </div>
              <div style="clear:both;"></div>
            </div>
          </div>
        </div><!-- /.module -->
      </div>
      <div class="span7">
        <div class="module">
          <div class="inner">
            <div id="tweets">
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Flex</strong></p>
                  <p><%= @board.Flex %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Flex %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Carving</strong></p>
                  <p><%= @board.Carving %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Carving %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Switch</strong></p>
                  <p><%= @board.Switch %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Switch %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Jibbing</strong></p>
                  <p><%= @board.Jibbing %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Jibbing %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Pipe</strong></p>
                  <p><%= @board.Pipe %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Pipe %>
                </div>
              </div>
              <div style="clear:both;"></div>
              <div class="tweet" style="clear:both;">
                <div style="float:left">
                  <p><strong>Jumps</strong></p>
                  <p><%= @board.Jumps %></p>
                </div>
                <div class="flakes" style="float:right; padding-top:5px">
                  <%= raw BoardsHelper.getReviewsValues @board.Jumps %>
                </div>
              </div>
              <div style="clear:both;"></div>
            </div>
          </div>
        </div><!-- /.module -->
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
  <div class="span4">
  <div class="row">
    <div class="span4">
      <div class="thumbnail" style="">
        <div style="max-width:160px; margin-top:8px; margin-bottom:8px; margin-left: auto; margin-right: auto;">
          广告位
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="thumbnail" style="">
        <div style="max-width:160px; margin-top:8px; margin-bottom:8px; margin-left: auto; margin-right: auto;">
          广告位
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="thumbnail" style="">
        <div class="imagesrotator" style="max-width:160px; margin-top:8px; margin-bottom:8px; margin-left: auto; margin-right: auto;">
          广告位
        </div>
      </div>
    </div>
  </div>
</div>
</div>
       </article>
   </div>
   <aside id="sidebar" class="" role="complementary">
   </aside>
</div>
  <!-- /#content -->
<%= link_to '编辑', [:edit, @board] %> |
<%= link_to '返回', boards_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ski2022</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="/css/bootstrap.css">
  <link rel="stylesheet" href="/css/bootstrap-responsive.css">
  <link rel="stylesheet" href="/css/app.css">
  <link rel="stylesheet" href="/css/lightbox.min.css">
  <script type='text/javascript' src='/js/jquery.lightbox.min.js'></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/ski/home.html.erb
<h1>Ski#home</h1>
<p>Find me in app/views/ski/home.html.erb</p>